const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');
const authRoutes = require('./routes/auth.routes');
const calendarIntegrationRoutes = require('./routes/calendarIntegration.routes');
const calendarRoutes = require('./routes/calendar.routes');
const projectRoutes = require('./routes/project.routes');
const taskRoutes = require('./routes/task.routes');
const approvalRoutes = require('./routes/approval.routes');
const roleRoutes = require('./routes/role.routes');
const taskMarkerRoutes = require('./routes/taskMarker.routes');
const auditLogRoutes = require('./routes/auditLog.routes');
dotenv.config();
const app = express();
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });
app.use(cors());
app.use(express.json());
app.use((req, res, next) => {
  req.prisma = prisma;
  next();
});
app.get('/', (req, res) => {
  res.json({ message: 'NextTask API läuft' });
});
app.use('/api/auth', authRoutes);
app.use('/api/calendar-integration', calendarIntegrationRoutes);
app.use('/api/calendar', calendarRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/tasks', taskRoutes);
app.use('/api/approvals', approvalRoutes);
app.use('/api/roles', roleRoutes);
app.use('/api/task-markers', taskMarkerRoutes);
app.use('/api/audit-logs', auditLogRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server läuft auf http://localhost:${PORT}`);
});
